language: c
script: ./travis-tool.sh run_tests
before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  - ./travis-tool.sh r_binary_install testthat
install:
  - ./travis-tool.sh install_deps
notifications:
  email:
    on_success: change
    on_failure: change
env:
  global:
    - WARNINGS_ARE_ERRORS=1
    - _R_CHECK_FORCE_SUGGESTS_=0
deploy:
  provider: releases
  api_key:
    secure: CSAGIjbkAWXfgy3okkKTqBy84C/wacHsDZ4yG8bWy1ZsrfHgrGdOTzyqqqmiwb923OirZFX+ni5/0YXCdFwEhqMqYXdj74X2kLW4IAe418ltgeLPnF9/0RfRnIpXPehnWbaVIz0EiEgz0snzPOQbwKAbMyHluAc0QVE2EBDBVJg=
  file: ls -1t *.tar.gz | head -n 1
  on:
    repo: ajdm/travisreleasetest
